name: Maven Relase

on:
  push:
    branches: [ master ]

jobs: 
  build_jar:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: eric2788/maven-jar-publish@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          java-version: 16
